// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKDZlcLtACBOB_Sgeq4X7h-uazL3Lm_OI',
    appId: '1:808285326497:web:aff03c40410fdd891974e0',
    messagingSenderId: '808285326497',
    projectId: 'karta-chat-app',
    authDomain: 'karta-chat-app.firebaseapp.com',
    storageBucket: 'karta-chat-app.firebasestorage.app',
    measurementId: 'G-Z41BYG5YBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLjfdkJ_8HjlUGsbBeK5EMRv4iVhIhYWo',
    appId: '1:808285326497:android:efeab637e5f848371974e0',
    messagingSenderId: '808285326497',
    projectId: 'karta-chat-app',
    storageBucket: 'karta-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG7NUx5HYpErtvLIqmGY8NXXKiRi0-2iM',
    appId: '1:808285326497:ios:180831409ae8c75b1974e0',
    messagingSenderId: '808285326497',
    projectId: 'karta-chat-app',
    storageBucket: 'karta-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.chattApp',
  );
}
